[window]
startup_mode = "Maximized"

[cursor]
style = { shape = "Beam" }

[font]
size = 13.5

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[colors.primary]
background = "#1C1C1C"
foreground = "#DDEEDD"

[colors.cursor]
cursor = "#a277ff"

[colors.selection]
text = "CellForeground"
background = "#29263c"

[colors.normal]
black = "#3D352A"
red = "#CD5C5C"
green = "#86AF80"
yellow = "#E8AE5B"
blue = "#6495ED"
magenta = "#DEB887"
cyan = "#B0C4DE"
white = "#BBAA99"

[colors.bright]
black = "#554444"
red = "#CC5533"
green = "#88AA22"
yellow = "#FFA75D"
blue = "#87CEEB"
magenta = "#996600"
cyan = "#B0C4DE"
white = "#DDCCBB"
